[project]
name = "backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[tasks]
start-server = "flask --app app run --debug"

[dependencies]
python = ">=3.12.3,<3.13"
flask = ">=3.0.3,<3.1"
pymongo = ">=4.7.2,<4.8"
flask-cors = ">=4.0.0,<4.1"
pyjwt = ">=2.8.0,<2.9"
