[project]
name = "backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[tasks]
start-server = "flask run --debug --port 5000"
start-db = "mongod --port 27017 --dbpath ./db" # mongodb on conda only on version 6, we need 7, so this is external
setup-db = 'mongoimport --db backend --collection books --file data/books.json --drop && mongosh data/replaceRoot.mongodb' # needs start-db, but async doesn't work; also $out is not replacing for some reason
# start = "pixi run start-server & pixi run start-db" # doesn't work


[dependencies]
python = ">=3.12.3,<3.13"
flask = ">=3.0.3,<3.1"
pymongo = ">=4.7.2,<4.8"
flask-cors = ">=4.0.0,<4.1"
pyjwt = ">=2.8.0,<2.9"
pixi-pycharm = ">=0.0.5,<0.1"
python-dotenv = ">=1.0.1,<1.1"
mongo-tools = ">=100.9.4,<100.10"
flask-pymongo = ">=2.3.0,<2.4"
